[server]
headless = true
runOnSave = true
fileWatcherType = "auto"

[browser]
gatherUsageStats = false

[theme]
base = "dark"
primaryColor = "#D4A574"
backgroundColor = "#2C2B28"
secondaryBackgroundColor = "#3D3B37"
textColor = "#ECECEC"
font = "sans serif"
